server:
  port: 8080
spring:
  profiles:
    active: dev
  application:
    name: "accounts"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "optional:configserver:${CONFIG_URL:http://localhost:8071}"
#      - "application_dev.yml"
#      - "application_qa.yml"

accounts:
  message: "Hello"
  contactDetails:
    name: "James"
    email: "james@test.com"
  onCallSupport:
    - 123-567
    - 123-678